### PR TITLE
Added project-everest, docs, assembly tags

### PR DESCRIPTION
**Pull request by terencehuynh**
- Added three tags: `project-everest`, `docs`, and `assembly`.
- Also made `npm start` point to `node generate.js`

### CODE REVIEW

**Comment by dabutvin** [comment]
@terencehuynh do you want to resolve the conflict in docs.md ?

**Comment by terencehuynh** [comment]
Will do @dabutvin

**Comment by terencehuynh** [comment]
Resolved conflicts @dabutvin 👍

**Comment by dabutvin** [comment]
:+1:

**Pull request merged**
